<!DOCTYPE html>
<html>
<head>
	<title>Thought Applied Creations<?php echo " | $page_title " ?></title>
	<link rel="stylesheet" type="text/css" href="bs4/css/bootstrap.min.css">
	<script type="text/javascript" src="bs4/js/jquery.min.js"></script>
  	<script type="text/javascript" src="bs4/js/popper.min.js"></script>
  	<script type="text/javascript" src="bs4/js/bootstrap.min.js"></script>
</head>
<body>

	<div class="container-fluid">
		<center>
		<br>
